development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://abzkbgztdpuntf:151e777c27c598ec0e07c8366be303cc579511d05dbde024a9a20c547b46734c@ec2-54-221-221-153.compute-1.amazonaws.com:5432/da2nlm6bbea8cm
  channel_prefix: HavingCows_production
